# language: nl
Functionaliteit: Test samenstellen van volledige naam van minderjarige en gezaghebbenden

  Regel: Volledige naam van de minderjarige wordt samengesteld uit naamvelden en geslacht van de minderjarige

    Scenario: volledigeNaam van minderjarige <omschrijving>
      Gegeven de minderjarige persoon 'minderjarige' met één ouder 'moeder'
      En heeft de volgende gegevens
        | naam                                 | waarde               |
        | voornamen (02.10)                    | <voornamen>          |
        | voornamen (diakrieten)               | <voornamen diak>     |
        | adellijke titel of predicaat (02.20) | <titel predicaat>    |
        | voorvoegsel (02.30)                  | <voorvoegsel>        |
        | geslachtsnaam (02.40)                | <geslachtsnaam>      |
        | geslachtsnaam (diakrieten)           | <geslachtsnaam diak> |
        | geslachtsaanduiding (04.10)          | <geslacht>           |
      Als 'gezag' wordt gevraagd van 'minderjarige'
      Dan is het gezag over 'minderjarige' eenhoofdig ouderlijk gezag met ouder 'moeder'
      En heeft de minderjarige de volgende gegevens
        | naam                | waarde           |
        | burgerservicenummer |        000000103 |
        | naam.volledigeNaam  | <volledige naam> |
        | leeftijd            |               17 |

      Voorbeelden:
        | voornamen                              | voornamen diak                         | titel predicaat | voorvoegsel | geslachtsnaam                     | geslachtsnaam diak | geslacht | volledige naam                                                                  | omschrijving                                       |
        | Christina Maria                        |                                        |                 |             | Maassen                           |                    | M        | Christina Maria Maassen                                                         | zonder voorvoegsel                                 |
        | Gerrit                                 |                                        |                 | den         | Braber                            |                    | M        | Gerrit den Braber                                                               | met voorvoegsel                                    |
        |                                        |                                        |                 |             | Obbadah                           |                    | M        | Obbadah                                                                         | naamketen                                          |
        | Mohamed                                |                                        |                 | El          | Rafi                              |                    | M        | Mohamed El Rafi                                                                 | voorvoegsel met hoofdletter                        |
        | Lisanty Teresita del nino Jesus Virgen | Lisanty Teresita del niño Jesús Virgen |                 | De las      | do Livramento de La Salete Jansz. |                    | M        | Lisanty Teresita del niño Jesús Virgen De las do Livramento de La Salete Jansz. | voornamen met diakrieten en geslachtsnaam met punt |
        | Anna                                   |                                        |                 |             | Ozil                              | Özil               | M        | Anna Özil                                                                       | geslachtsnaam met diakriet                         |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | V        | jonkvrouw Ariana van Hoogh                                                      | predicaat jonkvrouw                                |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | M        | jonkheer Ariana van Hoogh                                                       | predicaat jonkvrouw en geslacht man                |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | V        | jonkvrouw Ariana van Hoogh                                                      | predicaat jonkvrouw en geslacht onbekend           |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | M        | jonkheer Alex van Hoogh                                                         | predicaat jonkheer                                 |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | V        | jonkvrouw Alex van Hoogh                                                        | predicaat jonkheer en geslacht vrouw               |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | O        | jonkheer Alex van Hoogh                                                         | predicaat jonkheer en geslacht onbekend            |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | V        | Robin Sam gravin van den Aedel                                                  | adellijke titel graaf en geslacht vrouw            |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | M        | Robin Sam graaf van den Aedel                                                   | adellijke titel graaf en geslacht man              |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | O        | Robin Sam graaf van den Aedel                                                   | adellijke titel graaf en geslacht onbekend         |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | V        | Robin Sam gravin van den Aedel                                                  | adellijke titel gravin en geslacht vrouw           |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | M        | Robin Sam graaf van den Aedel                                                   | adellijke titel gravin en geslacht man             |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | O        | Robin Sam gravin van den Aedel                                                  | adellijke titel gravin en geslacht onbekend        |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | V        | Robin Sam barones van den Aedel                                                 | adellijke titel baron en geslacht vrouw            |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | M        | Robin Sam baron van den Aedel                                                   | adellijke titel baron en geslacht man              |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | O        | Robin Sam baron van den Aedel                                                   | adellijke titel baron en geslacht onbekend         |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | V        | Robin Sam barones van den Aedel                                                 | adellijke titel barones en geslacht vrouw          |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | M        | Robin Sam baron van den Aedel                                                   | adellijke titel barones en geslacht man            |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | O        | Robin Sam barones van den Aedel                                                 | adellijke titel barones en geslacht onbekend       |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | V        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertog en geslacht vrouw           |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | M        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertog en geslacht man             |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | O        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertog en geslacht onbekend        |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | V        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertogin en geslacht vrouw         |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | M        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertogin en geslacht man           |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | O        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertogin en geslacht onbekend      |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | V        | Robin Sam markiezin van den Aedel                                               | adellijke titel markies en geslacht vrouw          |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | M        | Robin Sam markies van den Aedel                                                 | adellijke titel markies en geslacht man            |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | O        | Robin Sam markies van den Aedel                                                 | adellijke titel markies en geslacht onbekend       |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | V        | Robin Sam markiezin van den Aedel                                               | adellijke titel markiezin en geslacht vrouw        |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | M        | Robin Sam markies van den Aedel                                                 | adellijke titel markiezin en geslacht man          |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | O        | Robin Sam markiezin van den Aedel                                               | adellijke titel markiezin en geslacht onbekend     |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | V        | Robin Sam prinses van den Aedel                                                 | adellijke titel prins en geslacht vrouw            |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | M        | Robin Sam prins van den Aedel                                                   | adellijke titel prins en geslacht man              |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | O        | Robin Sam prins van den Aedel                                                   | adellijke titel prins en geslacht onbekend         |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | V        | Robin Sam prinses van den Aedel                                                 | adellijke titel prinses en geslacht vrouw          |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | M        | Robin Sam prins van den Aedel                                                   | adellijke titel prinses en geslacht man            |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | O        | Robin Sam prinses van den Aedel                                                 | adellijke titel prinses en geslacht onbekend       |
        | Robin Sam                              |                                        | R               | van den     | Aedel                             |                    | V        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht vrouw           |
        | Robin Sam                              |                                        | R               | van den     | Aedel                             |                    | M        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht man             |
        | Robin Sam                              |                                        | R               | van  den    | Aedel                             |                    | O        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht onbekend        |

  Regel: Volledige naam van de minderjarige wordt samengesteld uit naamvelden en geslacht van de ouder

    Scenario: volledigeNaam van ouder <omschrijving>
      Gegeven de persoon 'moeder'
      * heeft de volgende gegevens
        | naam                                 | waarde               |
        | voornamen (02.10)                    | <voornamen>          |
        | voornamen (diakrieten)               | <voornamen diak>     |
        | adellijke titel of predicaat (02.20) | <titel predicaat>    |
        | voorvoegsel (02.30)                  | <voorvoegsel>        |
        | geslachtsnaam (02.40)                | <geslachtsnaam>      |
        | geslachtsnaam (diakrieten)           | <geslachtsnaam diak> |
        | geslachtsaanduiding (04.10)          | <geslacht>           |
      * is meerderjarig
      En de minderjarige persoon 'minderjarige' met één ouder 'moeder'
      Als 'gezag' wordt gevraagd van 'minderjarige'
      Dan is het gezag over 'minderjarige' eenhoofdig ouderlijk gezag met ouder 'moeder'
      En heeft de ouder de volgende gegevens
        | naam                | waarde           |
        | burgerservicenummer |        000000101 |
        | naam.volledigeNaam  | <volledige naam> |

      Voorbeelden:
        | voornamen                              | voornamen diak                         | titel predicaat | voorvoegsel | geslachtsnaam                     | geslachtsnaam diak | geslacht | volledige naam                                                                  | omschrijving                                       |
        | Christina Maria                        |                                        |                 |             | Maassen                           |                    | M        | Christina Maria Maassen                                                         | zonder voorvoegsel                                 |
        | Gerrit                                 |                                        |                 | den         | Braber                            |                    | M        | Gerrit den Braber                                                               | met voorvoegsel                                    |
        |                                        |                                        |                 |             | Obbadah                           |                    | M        | Obbadah                                                                         | naamketen                                          |
        | Mohamed                                |                                        |                 | El          | Rafi                              |                    | M        | Mohamed El Rafi                                                                 | voorvoegsel met hoofdletter                        |
        | Lisanty Teresita del nino Jesus Virgen | Lisanty Teresita del niño Jesús Virgen |                 | De las      | do Livramento de La Salete Jansz. |                    | M        | Lisanty Teresita del niño Jesús Virgen De las do Livramento de La Salete Jansz. | voornamen met diakrieten en geslachtsnaam met punt |
        | Anna                                   |                                        |                 |             | Ozil                              | Özil               | M        | Anna Özil                                                                       | geslachtsnaam met diakriet                         |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | V        | jonkvrouw Ariana van Hoogh                                                      | predicaat jonkvrouw                                |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | M        | jonkheer Ariana van Hoogh                                                       | predicaat jonkvrouw en geslacht man                |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | V        | jonkvrouw Ariana van Hoogh                                                      | predicaat jonkvrouw en geslacht onbekend           |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | M        | jonkheer Alex van Hoogh                                                         | predicaat jonkheer                                 |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | V        | jonkvrouw Alex van Hoogh                                                        | predicaat jonkheer en geslacht vrouw               |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | O        | jonkheer Alex van Hoogh                                                         | predicaat jonkheer en geslacht onbekend            |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | V        | Robin Sam gravin van den Aedel                                                  | adellijke titel graaf en geslacht vrouw            |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | M        | Robin Sam graaf van den Aedel                                                   | adellijke titel graaf en geslacht man              |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | O        | Robin Sam graaf van den Aedel                                                   | adellijke titel graaf en geslacht onbekend         |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | V        | Robin Sam gravin van den Aedel                                                  | adellijke titel gravin en geslacht vrouw           |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | M        | Robin Sam graaf van den Aedel                                                   | adellijke titel gravin en geslacht man             |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | O        | Robin Sam gravin van den Aedel                                                  | adellijke titel gravin en geslacht onbekend        |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | V        | Robin Sam barones van den Aedel                                                 | adellijke titel baron en geslacht vrouw            |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | M        | Robin Sam baron van den Aedel                                                   | adellijke titel baron en geslacht man              |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | O        | Robin Sam baron van den Aedel                                                   | adellijke titel baron en geslacht onbekend         |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | V        | Robin Sam barones van den Aedel                                                 | adellijke titel barones en geslacht vrouw          |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | M        | Robin Sam baron van den Aedel                                                   | adellijke titel barones en geslacht man            |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | O        | Robin Sam barones van den Aedel                                                 | adellijke titel barones en geslacht onbekend       |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | V        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertog en geslacht vrouw           |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | M        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertog en geslacht man             |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | O        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertog en geslacht onbekend        |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | V        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertogin en geslacht vrouw         |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | M        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertogin en geslacht man           |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | O        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertogin en geslacht onbekend      |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | V        | Robin Sam markiezin van den Aedel                                               | adellijke titel markies en geslacht vrouw          |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | M        | Robin Sam markies van den Aedel                                                 | adellijke titel markies en geslacht man            |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | O        | Robin Sam markies van den Aedel                                                 | adellijke titel markies en geslacht onbekend       |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | V        | Robin Sam markiezin van den Aedel                                               | adellijke titel markiezin en geslacht vrouw        |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | M        | Robin Sam markies van den Aedel                                                 | adellijke titel markiezin en geslacht man          |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | O        | Robin Sam markiezin van den Aedel                                               | adellijke titel markiezin en geslacht onbekend     |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | V        | Robin Sam prinses van den Aedel                                                 | adellijke titel prins en geslacht vrouw            |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | M        | Robin Sam prins van den Aedel                                                   | adellijke titel prins en geslacht man              |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | O        | Robin Sam prins van den Aedel                                                   | adellijke titel prins en geslacht onbekend         |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | V        | Robin Sam prinses van den Aedel                                                 | adellijke titel prinses en geslacht vrouw          |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | M        | Robin Sam prins van den Aedel                                                   | adellijke titel prinses en geslacht man            |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | O        | Robin Sam prinses van den Aedel                                                 | adellijke titel prinses en geslacht onbekend       |
        | Robin Sam                              |                                        | R               | van den     | Aedel                             |                    | V        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht vrouw           |
        | Robin Sam                              |                                        | R               | van den     | Aedel                             |                    | M        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht man             |
        | Robin Sam                              |                                        | R               | van  den    | Aedel                             |                    | O        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht onbekend        |

  Regel: Volledige naam van de minderjarige wordt samengesteld uit naamvelden en geslacht van de derde

    Scenario: volledigeNaam van derde <omschrijving>
      Gegeven de persoon 'partner'
      * heeft de volgende gegevens
        | naam                                 | waarde               |
        | voornamen (02.10)                    | <voornamen>          |
        | voornamen (diakrieten)               | <voornamen diak>     |
        | adellijke titel of predicaat (02.20) | <titel predicaat>    |
        | voorvoegsel (02.30)                  | <voorvoegsel>        |
        | geslachtsnaam (02.40)                | <geslachtsnaam>      |
        | geslachtsnaam (diakrieten)           | <geslachtsnaam diak> |
        | geslachtsaanduiding (04.10)          | <geslacht>           |
      * is meerderjarig
      En de minderjarige persoon 'minderjarige' met één ouder 'moeder' die gehuwd is met 'partner'
      Als 'gezag' wordt gevraagd van 'minderjarige'
      Dan is het gezag over 'minderjarige' gezamenlijk gezag met ouder 'moeder' en derde 'partner'
      En heeft de derde de volgende gegevens
        | naam                | waarde           |
        | burgerservicenummer |        000000102 |
        | naam.volledigeNaam  | <volledige naam> |

      Voorbeelden:
        | voornamen                              | voornamen diak                         | titel predicaat | voorvoegsel | geslachtsnaam                     | geslachtsnaam diak | geslacht | volledige naam                                                                  | omschrijving                                       |
        | Christina Maria                        |                                        |                 |             | Maassen                           |                    | M        | Christina Maria Maassen                                                         | zonder voorvoegsel                                 |
        | Gerrit                                 |                                        |                 | den         | Braber                            |                    | M        | Gerrit den Braber                                                               | met voorvoegsel                                    |
        |                                        |                                        |                 |             | Obbadah                           |                    | M        | Obbadah                                                                         | naamketen                                          |
        | Mohamed                                |                                        |                 | El          | Rafi                              |                    | M        | Mohamed El Rafi                                                                 | voorvoegsel met hoofdletter                        |
        | Lisanty Teresita del nino Jesus Virgen | Lisanty Teresita del niño Jesús Virgen |                 | De las      | do Livramento de La Salete Jansz. |                    | M        | Lisanty Teresita del niño Jesús Virgen De las do Livramento de La Salete Jansz. | voornamen met diakrieten en geslachtsnaam met punt |
        | Anna                                   |                                        |                 |             | Ozil                              | Özil               | M        | Anna Özil                                                                       | geslachtsnaam met diakriet                         |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | V        | jonkvrouw Ariana van Hoogh                                                      | predicaat jonkvrouw                                |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | M        | jonkheer Ariana van Hoogh                                                       | predicaat jonkvrouw en geslacht man                |
        | Ariana                                 |                                        | JV              | van         | Hoogh                             |                    | V        | jonkvrouw Ariana van Hoogh                                                      | predicaat jonkvrouw en geslacht onbekend           |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | M        | jonkheer Alex van Hoogh                                                         | predicaat jonkheer                                 |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | V        | jonkvrouw Alex van Hoogh                                                        | predicaat jonkheer en geslacht vrouw               |
        | Alex                                   |                                        | JH              | van         | Hoogh                             |                    | O        | jonkheer Alex van Hoogh                                                         | predicaat jonkheer en geslacht onbekend            |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | V        | Robin Sam gravin van den Aedel                                                  | adellijke titel graaf en geslacht vrouw            |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | M        | Robin Sam graaf van den Aedel                                                   | adellijke titel graaf en geslacht man              |
        | Robin Sam                              |                                        | G               | van den     | Aedel                             |                    | O        | Robin Sam graaf van den Aedel                                                   | adellijke titel graaf en geslacht onbekend         |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | V        | Robin Sam gravin van den Aedel                                                  | adellijke titel gravin en geslacht vrouw           |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | M        | Robin Sam graaf van den Aedel                                                   | adellijke titel gravin en geslacht man             |
        | Robin Sam                              |                                        | GI              | van den     | Aedel                             |                    | O        | Robin Sam gravin van den Aedel                                                  | adellijke titel gravin en geslacht onbekend        |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | V        | Robin Sam barones van den Aedel                                                 | adellijke titel baron en geslacht vrouw            |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | M        | Robin Sam baron van den Aedel                                                   | adellijke titel baron en geslacht man              |
        | Robin Sam                              |                                        | B               | van den     | Aedel                             |                    | O        | Robin Sam baron van den Aedel                                                   | adellijke titel baron en geslacht onbekend         |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | V        | Robin Sam barones van den Aedel                                                 | adellijke titel barones en geslacht vrouw          |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | M        | Robin Sam baron van den Aedel                                                   | adellijke titel barones en geslacht man            |
        | Robin Sam                              |                                        | BS              | van den     | Aedel                             |                    | O        | Robin Sam barones van den Aedel                                                 | adellijke titel barones en geslacht onbekend       |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | V        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertog en geslacht vrouw           |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | M        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertog en geslacht man             |
        | Robin Sam                              |                                        | H               | van den     | Aedel                             |                    | O        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertog en geslacht onbekend        |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | V        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertogin en geslacht vrouw         |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | M        | Robin Sam hertog van den Aedel                                                  | adellijke titel hertogin en geslacht man           |
        | Robin Sam                              |                                        | HI              | van den     | Aedel                             |                    | O        | Robin Sam hertogin van den Aedel                                                | adellijke titel hertogin en geslacht onbekend      |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | V        | Robin Sam markiezin van den Aedel                                               | adellijke titel markies en geslacht vrouw          |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | M        | Robin Sam markies van den Aedel                                                 | adellijke titel markies en geslacht man            |
        | Robin Sam                              |                                        | M               | van den     | Aedel                             |                    | O        | Robin Sam markies van den Aedel                                                 | adellijke titel markies en geslacht onbekend       |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | V        | Robin Sam markiezin van den Aedel                                               | adellijke titel markiezin en geslacht vrouw        |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | M        | Robin Sam markies van den Aedel                                                 | adellijke titel markiezin en geslacht man          |
        | Robin Sam                              |                                        | MI              | van den     | Aedel                             |                    | O        | Robin Sam markiezin van den Aedel                                               | adellijke titel markiezin en geslacht onbekend     |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | V        | Robin Sam prinses van den Aedel                                                 | adellijke titel prins en geslacht vrouw            |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | M        | Robin Sam prins van den Aedel                                                   | adellijke titel prins en geslacht man              |
        | Robin Sam                              |                                        | P               | van den     | Aedel                             |                    | O        | Robin Sam prins van den Aedel                                                   | adellijke titel prins en geslacht onbekend         |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | V        | Robin Sam prinses van den Aedel                                                 | adellijke titel prinses en geslacht vrouw          |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | M        | Robin Sam prins van den Aedel                                                   | adellijke titel prinses en geslacht man            |
        | Robin Sam                              |                                        | PS              | van den     | Aedel                             |                    | O        | Robin Sam prinses van den Aedel                                                 | adellijke titel prinses en geslacht onbekend       |
        | Robin Sam                              |                                        | R               | van den     | Aedel                             |                    | V        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht vrouw           |
        | Robin Sam                              |                                        | R               | van den     | Aedel                             |                    | M        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht man             |
        | Robin Sam                              |                                        | R               | van  den    | Aedel                             |                    | O        | Robin Sam ridder van den Aedel                                                  | adellijke titel ridder en geslacht onbekend        |
